import 'package:example/src/icon_detail.dart';
import 'package:iconly/iconly.dart';

final lightIcons = [
  IconlyDetail(type: 'IconlyLight', title: 'activity', iconData: IconlyLight.activity),
  IconlyDetail(type: 'IconlyLight', title: 'add_user', iconData: IconlyLight.add_user),
  IconlyDetail(type: 'IconlyLight', title: 'arrow_down', iconData: IconlyLight.arrow_down),
  IconlyDetail(type: 'IconlyLight', title: 'arrow_down_2', iconData: IconlyLight.arrow_down_2),
  IconlyDetail(type: 'IconlyLight', title: 'arrow_down_3', iconData: IconlyLight.arrow_down_3),
  IconlyDetail(
      type: 'IconlyLight', title: 'arrow_down_circle', iconData: IconlyLight.arrow_down_circle),
  IconlyDetail(
      type: 'IconlyLight', title: 'arrow_down_square', iconData: IconlyLight.arrow_down_square),
  IconlyDetail(type: 'IconlyLight', title: 'arrow_left', iconData: IconlyLight.arrow_left),
  IconlyDetail(type: 'IconlyLight', title: 'arrow_left_2', iconData: IconlyLight.arrow_left_2),
  IconlyDetail(type: 'IconlyLight', title: 'arrow_left_3', iconData: IconlyLight.arrow_left_3),
  IconlyDetail(
      type: 'IconlyLight', title: 'arrow_left_circle', iconData: IconlyLight.arrow_left_circle),
  IconlyDetail(
      type: 'IconlyLight', title: 'arrow_left_square', iconData: IconlyLight.arrow_left_square),
  IconlyDetail(type: 'IconlyLight', title: 'arrow_right', iconData: IconlyLight.arrow_right),
  IconlyDetail(type: 'IconlyLight', title: 'arrow_right_2', iconData: IconlyLight.arrow_right_2),
  IconlyDetail(type: 'IconlyLight', title: 'arrow_right_3', iconData: IconlyLight.arrow_right_3),
  IconlyDetail(
      type: 'IconlyLight', title: 'arrow_right_circle', iconData: IconlyLight.arrow_right_circle),
  IconlyDetail(
      type: 'IconlyLight', title: 'arrow_right_square', iconData: IconlyLight.arrow_right_square),
  IconlyDetail(type: 'IconlyLight', title: 'arrow_up', iconData: IconlyLight.arrow_up),
  IconlyDetail(type: 'IconlyLight', title: 'arrow_up_2', iconData: IconlyLight.arrow_up_2),
  IconlyDetail(type: 'IconlyLight', title: 'arrow_up_3', iconData: IconlyLight.arrow_up_3),
  IconlyDetail(
      type: 'IconlyLight', title: 'arrow_up_circle', iconData: IconlyLight.arrow_up_circle),
  IconlyDetail(
      type: 'IconlyLight', title: 'arrow_up_square', iconData: IconlyLight.arrow_up_square),
  IconlyDetail(type: 'IconlyLight', title: 'bag', iconData: IconlyLight.bag),
  IconlyDetail(type: 'IconlyLight', title: 'bag_2', iconData: IconlyLight.bag_2),
  IconlyDetail(type: 'IconlyLight', title: 'bookmark', iconData: IconlyLight.bookmark),
  IconlyDetail(type: 'IconlyLight', title: 'buy', iconData: IconlyLight.buy),
  IconlyDetail(type: 'IconlyLight', title: 'calendar', iconData: IconlyLight.calendar),
  IconlyDetail(type: 'IconlyLight', title: 'call', iconData: IconlyLight.call),
  IconlyDetail(type: 'IconlyLight', title: 'call_missed', iconData: IconlyLight.call_missed),
  IconlyDetail(type: 'IconlyLight', title: 'call_silent', iconData: IconlyLight.call_silent),
  IconlyDetail(type: 'IconlyLight', title: 'calling', iconData: IconlyLight.calling),
  IconlyDetail(type: 'IconlyLight', title: 'camera', iconData: IconlyLight.camera),
  IconlyDetail(type: 'IconlyLight', title: 'category', iconData: IconlyLight.category),
  IconlyDetail(type: 'IconlyLight', title: 'chart', iconData: IconlyLight.chart),
  IconlyDetail(type: 'IconlyLight', title: 'chat', iconData: IconlyLight.chat),
  IconlyDetail(type: 'IconlyLight', title: 'close_square', iconData: IconlyLight.close_square),
  IconlyDetail(type: 'IconlyLight', title: 'danger', iconData: IconlyLight.danger),
  IconlyDetail(type: 'IconlyLight', title: 'delete', iconData: IconlyLight.delete),
  IconlyDetail(type: 'IconlyLight', title: 'discount', iconData: IconlyLight.discount),
  IconlyDetail(type: 'IconlyLight', title: 'discovery', iconData: IconlyLight.discovery),
  IconlyDetail(type: 'IconlyLight', title: 'document', iconData: IconlyLight.document),
  IconlyDetail(type: 'IconlyLight', title: 'download', iconData: IconlyLight.download),
  IconlyDetail(type: 'IconlyLight', title: 'edit', iconData: IconlyLight.edit),
  IconlyDetail(type: 'IconlyLight', title: 'edit_square', iconData: IconlyLight.edit_square),
  IconlyDetail(type: 'IconlyLight', title: 'filter', iconData: IconlyLight.filter),
  IconlyDetail(type: 'IconlyLight', title: 'filter_2', iconData: IconlyLight.filter_2),
  IconlyDetail(type: 'IconlyLight', title: 'folder', iconData: IconlyLight.folder),
  IconlyDetail(type: 'IconlyLight', title: 'game', iconData: IconlyLight.game),
  IconlyDetail(type: 'IconlyLight', title: 'graph', iconData: IconlyLight.graph),
  IconlyDetail(type: 'IconlyLight', title: 'heart', iconData: IconlyLight.heart),
  IconlyDetail(type: 'IconlyLight', title: 'hide', iconData: IconlyLight.hide),
  IconlyDetail(type: 'IconlyLight', title: 'home', iconData: IconlyLight.home),
  IconlyDetail(type: 'IconlyLight', title: 'image', iconData: IconlyLight.image),
  IconlyDetail(type: 'IconlyLight', title: 'image_2', iconData: IconlyLight.image_2),
  IconlyDetail(type: 'IconlyLight', title: 'info_circle', iconData: IconlyLight.info_circle),
  IconlyDetail(type: 'IconlyLight', title: 'info_square', iconData: IconlyLight.info_square),
  IconlyDetail(type: 'IconlyLight', title: 'location', iconData: IconlyLight.location),
  IconlyDetail(type: 'IconlyLight', title: 'lock', iconData: IconlyLight.lock),
  IconlyDetail(type: 'IconlyLight', title: 'login', iconData: IconlyLight.login),
  IconlyDetail(type: 'IconlyLight', title: 'logout', iconData: IconlyLight.logout),
  IconlyDetail(type: 'IconlyLight', title: 'message', iconData: IconlyLight.message),
  IconlyDetail(type: 'IconlyLight', title: 'more_circle', iconData: IconlyLight.more_circle),
  IconlyDetail(type: 'IconlyLight', title: 'more_square', iconData: IconlyLight.more_square),
  IconlyDetail(type: 'IconlyLight', title: 'notification', iconData: IconlyLight.notification),
  IconlyDetail(type: 'IconlyLight', title: 'paper', iconData: IconlyLight.paper),
  IconlyDetail(type: 'IconlyLight', title: 'paper_download', iconData: IconlyLight.paper_download),
  IconlyDetail(type: 'IconlyLight', title: 'paper_fail', iconData: IconlyLight.paper_fail),
  IconlyDetail(type: 'IconlyLight', title: 'paper_negative', iconData: IconlyLight.paper_negative),
  IconlyDetail(type: 'IconlyLight', title: 'paper_plus', iconData: IconlyLight.paper_plus),
  IconlyDetail(type: 'IconlyLight', title: 'paper_upload', iconData: IconlyLight.paper_upload),
  IconlyDetail(type: 'IconlyLight', title: 'password', iconData: IconlyLight.password),
  IconlyDetail(type: 'IconlyLight', title: 'play', iconData: IconlyLight.play),
  IconlyDetail(type: 'IconlyLight', title: 'plus', iconData: IconlyLight.plus),
  IconlyDetail(type: 'IconlyLight', title: 'profile', iconData: IconlyLight.profile),
  IconlyDetail(type: 'IconlyLight', title: 'scan', iconData: IconlyLight.scan),
  IconlyDetail(type: 'IconlyLight', title: 'search', iconData: IconlyLight.search),
  IconlyDetail(type: 'IconlyLight', title: 'send', iconData: IconlyLight.send),
  IconlyDetail(type: 'IconlyLight', title: 'setting', iconData: IconlyLight.setting),
  IconlyDetail(type: 'IconlyLight', title: 'shield_done', iconData: IconlyLight.shield_done),
  IconlyDetail(type: 'IconlyLight', title: 'shield_fail', iconData: IconlyLight.shield_fail),
  IconlyDetail(type: 'IconlyLight', title: 'show', iconData: IconlyLight.show),
  IconlyDetail(type: 'IconlyLight', title: 'star', iconData: IconlyLight.star),
  IconlyDetail(type: 'IconlyLight', title: 'swap', iconData: IconlyLight.swap),
  IconlyDetail(type: 'IconlyLight', title: 'tick_square', iconData: IconlyLight.tick_square),
  IconlyDetail(type: 'IconlyLight', title: 'ticket', iconData: IconlyLight.ticket),
  IconlyDetail(type: 'IconlyLight', title: 'ticket_star', iconData: IconlyLight.ticket_star),
  IconlyDetail(type: 'IconlyLight', title: 'time_circle', iconData: IconlyLight.time_circle),
  IconlyDetail(type: 'IconlyLight', title: 'time_square', iconData: IconlyLight.time_square),
  IconlyDetail(type: 'IconlyLight', title: 'unlock', iconData: IconlyLight.unlock),
  IconlyDetail(type: 'IconlyLight', title: 'upload', iconData: IconlyLight.upload),
  IconlyDetail(type: 'IconlyLight', title: 'user', iconData: IconlyLight.user),
  IconlyDetail(type: 'IconlyLight', title: 'user_1', iconData: IconlyLight.user_1),
  IconlyDetail(type: 'IconlyLight', title: 'video', iconData: IconlyLight.video),
  IconlyDetail(type: 'IconlyLight', title: 'voice', iconData: IconlyLight.voice),
  IconlyDetail(type: 'IconlyLight', title: 'voice_2', iconData: IconlyLight.voice_2),
  IconlyDetail(type: 'IconlyLight', title: 'volume_down', iconData: IconlyLight.volume_down),
  IconlyDetail(type: 'IconlyLight', title: 'volume_off', iconData: IconlyLight.volume_off),
  IconlyDetail(type: 'IconlyLight', title: 'volume_up', iconData: IconlyLight.volume_up),
  IconlyDetail(type: 'IconlyLight', title: 'wallet', iconData: IconlyLight.wallet),
  IconlyDetail(type: 'IconlyLight', title: 'work', iconData: IconlyLight.work),
];

final brokenIcons = [
  IconlyDetail(type: 'IconlyBroken', title: 'activity', iconData: IconlyBroken.activity),
  IconlyDetail(type: 'IconlyBroken', title: 'add_user', iconData: IconlyBroken.add_user),
  IconlyDetail(type: 'IconlyBroken', title: 'arrow_down', iconData: IconlyBroken.arrow_down),
  IconlyDetail(type: 'IconlyBroken', title: 'arrow_down_2', iconData: IconlyBroken.arrow_down_2),
  IconlyDetail(type: 'IconlyBroken', title: 'arrow_down_3', iconData: IconlyBroken.arrow_down_3),
  IconlyDetail(
      type: 'IconlyBroken', title: 'arrow_down_circle', iconData: IconlyBroken.arrow_down_circle),
  IconlyDetail(
      type: 'IconlyBroken', title: 'arrow_down_square', iconData: IconlyBroken.arrow_down_square),
  IconlyDetail(type: 'IconlyBroken', title: 'arrow_left', iconData: IconlyBroken.arrow_left),
  IconlyDetail(type: 'IconlyBroken', title: 'arrow_left_2', iconData: IconlyBroken.arrow_left_2),
  IconlyDetail(type: 'IconlyBroken', title: 'arrow_left_3', iconData: IconlyBroken.arrow_left_3),
  IconlyDetail(
      type: 'IconlyBroken', title: 'arrow_left_circle', iconData: IconlyBroken.arrow_left_circle),
  IconlyDetail(
      type: 'IconlyBroken', title: 'arrow_left_square', iconData: IconlyBroken.arrow_left_square),
  IconlyDetail(type: 'IconlyBroken', title: 'arrow_right', iconData: IconlyBroken.arrow_right),
  IconlyDetail(type: 'IconlyBroken', title: 'arrow_right_2', iconData: IconlyBroken.arrow_right_2),
  IconlyDetail(type: 'IconlyBroken', title: 'arrow_right_3', iconData: IconlyBroken.arrow_right_3),
  IconlyDetail(
      type: 'IconlyBroken', title: 'arrow_right_circle', iconData: IconlyBroken.arrow_right_circle),
  IconlyDetail(
      type: 'IconlyBroken', title: 'arrow_right_square', iconData: IconlyBroken.arrow_right_square),
  IconlyDetail(type: 'IconlyBroken', title: 'arrow_up', iconData: IconlyBroken.arrow_up),
  IconlyDetail(type: 'IconlyBroken', title: 'arrow_up_2', iconData: IconlyBroken.arrow_up_2),
  IconlyDetail(type: 'IconlyBroken', title: 'arrow_up_3', iconData: IconlyBroken.arrow_up_3),
  IconlyDetail(
      type: 'IconlyBroken', title: 'arrow_up_circle', iconData: IconlyBroken.arrow_up_circle),
  IconlyDetail(
      type: 'IconlyBroken', title: 'arrow_up_square', iconData: IconlyBroken.arrow_up_square),
  IconlyDetail(type: 'IconlyBroken', title: 'bag', iconData: IconlyBroken.bag),
  IconlyDetail(type: 'IconlyBroken', title: 'bag_2', iconData: IconlyBroken.bag_2),
  IconlyDetail(type: 'IconlyBroken', title: 'bookmark', iconData: IconlyBroken.bookmark),
  IconlyDetail(type: 'IconlyBroken', title: 'buy', iconData: IconlyBroken.buy),
  IconlyDetail(type: 'IconlyBroken', title: 'calendar', iconData: IconlyBroken.calendar),
  IconlyDetail(type: 'IconlyBroken', title: 'call', iconData: IconlyBroken.call),
  IconlyDetail(type: 'IconlyBroken', title: 'call_missed', iconData: IconlyBroken.call_missed),
  IconlyDetail(type: 'IconlyBroken', title: 'call_silent', iconData: IconlyBroken.call_silent),
  IconlyDetail(type: 'IconlyBroken', title: 'calling', iconData: IconlyBroken.calling),
  IconlyDetail(type: 'IconlyBroken', title: 'camera', iconData: IconlyBroken.camera),
  IconlyDetail(type: 'IconlyBroken', title: 'category', iconData: IconlyBroken.category),
  IconlyDetail(type: 'IconlyBroken', title: 'chart', iconData: IconlyBroken.chart),
  IconlyDetail(type: 'IconlyBroken', title: 'chat', iconData: IconlyBroken.chat),
  IconlyDetail(type: 'IconlyBroken', title: 'close_square', iconData: IconlyBroken.close_square),
  IconlyDetail(type: 'IconlyBroken', title: 'danger', iconData: IconlyBroken.danger),
  IconlyDetail(type: 'IconlyBroken', title: 'delete', iconData: IconlyBroken.delete),
  IconlyDetail(type: 'IconlyBroken', title: 'discount', iconData: IconlyBroken.discount),
  IconlyDetail(type: 'IconlyBroken', title: 'discovery', iconData: IconlyBroken.discovery),
  IconlyDetail(type: 'IconlyBroken', title: 'document', iconData: IconlyBroken.document),
  IconlyDetail(type: 'IconlyBroken', title: 'download', iconData: IconlyBroken.download),
  IconlyDetail(type: 'IconlyBroken', title: 'edit', iconData: IconlyBroken.edit),
  IconlyDetail(type: 'IconlyBroken', title: 'edit_square', iconData: IconlyBroken.edit_square),
  IconlyDetail(type: 'IconlyBroken', title: 'filter', iconData: IconlyBroken.filter),
  IconlyDetail(type: 'IconlyBroken', title: 'filter_2', iconData: IconlyBroken.filter_2),
  IconlyDetail(type: 'IconlyBroken', title: 'folder', iconData: IconlyBroken.folder),
  IconlyDetail(type: 'IconlyBroken', title: 'game', iconData: IconlyBroken.game),
  IconlyDetail(type: 'IconlyBroken', title: 'graph', iconData: IconlyBroken.graph),
  IconlyDetail(type: 'IconlyBroken', title: 'heart', iconData: IconlyBroken.heart),
  IconlyDetail(type: 'IconlyBroken', title: 'hide', iconData: IconlyBroken.hide),
  IconlyDetail(type: 'IconlyBroken', title: 'home', iconData: IconlyBroken.home),
  IconlyDetail(type: 'IconlyBroken', title: 'image', iconData: IconlyBroken.image),
  IconlyDetail(type: 'IconlyBroken', title: 'image_2', iconData: IconlyBroken.image_2),
  IconlyDetail(type: 'IconlyBroken', title: 'info_circle', iconData: IconlyBroken.info_circle),
  IconlyDetail(type: 'IconlyBroken', title: 'info_square', iconData: IconlyBroken.info_square),
  IconlyDetail(type: 'IconlyBroken', title: 'location', iconData: IconlyBroken.location),
  IconlyDetail(type: 'IconlyBroken', title: 'lock', iconData: IconlyBroken.lock),
  IconlyDetail(type: 'IconlyBroken', title: 'login', iconData: IconlyBroken.login),
  IconlyDetail(type: 'IconlyBroken', title: 'logout', iconData: IconlyBroken.logout),
  IconlyDetail(type: 'IconlyBroken', title: 'message', iconData: IconlyBroken.message),
  IconlyDetail(type: 'IconlyBroken', title: 'more_circle', iconData: IconlyBroken.more_circle),
  IconlyDetail(type: 'IconlyBroken', title: 'more_square', iconData: IconlyBroken.more_square),
  IconlyDetail(type: 'IconlyBroken', title: 'notification', iconData: IconlyBroken.notification),
  IconlyDetail(type: 'IconlyBroken', title: 'paper', iconData: IconlyBroken.paper),
  IconlyDetail(
      type: 'IconlyBroken', title: 'paper_download', iconData: IconlyBroken.paper_download),
  IconlyDetail(type: 'IconlyBroken', title: 'paper_fail', iconData: IconlyBroken.paper_fail),
  IconlyDetail(
      type: 'IconlyBroken', title: 'paper_negative', iconData: IconlyBroken.paper_negative),
  IconlyDetail(type: 'IconlyBroken', title: 'paper_plus', iconData: IconlyBroken.paper_plus),
  IconlyDetail(type: 'IconlyBroken', title: 'paper_upload', iconData: IconlyBroken.paper_upload),
  IconlyDetail(type: 'IconlyBroken', title: 'password', iconData: IconlyBroken.password),
  IconlyDetail(type: 'IconlyBroken', title: 'play', iconData: IconlyBroken.play),
  IconlyDetail(type: 'IconlyBroken', title: 'plus', iconData: IconlyBroken.plus),
  IconlyDetail(type: 'IconlyBroken', title: 'profile', iconData: IconlyBroken.profile),
  IconlyDetail(type: 'IconlyBroken', title: 'scan', iconData: IconlyBroken.scan),
  IconlyDetail(type: 'IconlyBroken', title: 'search', iconData: IconlyBroken.search),
  IconlyDetail(type: 'IconlyBroken', title: 'send', iconData: IconlyBroken.send),
  IconlyDetail(type: 'IconlyBroken', title: 'setting', iconData: IconlyBroken.setting),
  IconlyDetail(type: 'IconlyBroken', title: 'shield_done', iconData: IconlyBroken.shield_done),
  IconlyDetail(type: 'IconlyBroken', title: 'shield_fail', iconData: IconlyBroken.shield_fail),
  IconlyDetail(type: 'IconlyBroken', title: 'show', iconData: IconlyBroken.show),
  IconlyDetail(type: 'IconlyBroken', title: 'star', iconData: IconlyBroken.star),
  IconlyDetail(type: 'IconlyBroken', title: 'swap', iconData: IconlyBroken.swap),
  IconlyDetail(type: 'IconlyBroken', title: 'tick_square', iconData: IconlyBroken.tick_square),
  IconlyDetail(type: 'IconlyBroken', title: 'ticket', iconData: IconlyBroken.ticket),
  IconlyDetail(type: 'IconlyBroken', title: 'ticket_star', iconData: IconlyBroken.ticket_star),
  IconlyDetail(type: 'IconlyBroken', title: 'time_circle', iconData: IconlyBroken.time_circle),
  IconlyDetail(type: 'IconlyBroken', title: 'times_quare', iconData: IconlyBroken.times_quare),
  IconlyDetail(type: 'IconlyBroken', title: 'unlock', iconData: IconlyBroken.unlock),
  IconlyDetail(type: 'IconlyBroken', title: 'upload', iconData: IconlyBroken.upload),
  IconlyDetail(type: 'IconlyBroken', title: 'user_2', iconData: IconlyBroken.user_2),
  IconlyDetail(type: 'IconlyBroken', title: 'user_3', iconData: IconlyBroken.user_3),
  IconlyDetail(type: 'IconlyBroken', title: 'video', iconData: IconlyBroken.video),
  IconlyDetail(type: 'IconlyBroken', title: 'voice', iconData: IconlyBroken.voice),
  IconlyDetail(type: 'IconlyBroken', title: 'voice_2', iconData: IconlyBroken.voice_2),
  IconlyDetail(type: 'IconlyBroken', title: 'volume_down', iconData: IconlyBroken.volume_down),
  IconlyDetail(type: 'IconlyBroken', title: 'volume_off', iconData: IconlyBroken.volume_off),
  IconlyDetail(type: 'IconlyBroken', title: 'volume_up', iconData: IconlyBroken.volume_up),
  IconlyDetail(type: 'IconlyBroken', title: 'wallet', iconData: IconlyBroken.wallet),
  IconlyDetail(type: 'IconlyBroken', title: 'work', iconData: IconlyBroken.work),
];

final boldIcons = [
  IconlyDetail(type: 'IconlyBold', title: 'activity', iconData: IconlyBold.activity),
  IconlyDetail(type: 'IconlyBold', title: 'add_user', iconData: IconlyBold.add_user),
  IconlyDetail(type: 'IconlyBold', title: 'arrow_down', iconData: IconlyBold.arrow_down),
  IconlyDetail(type: 'IconlyBold', title: 'arrow_down_2', iconData: IconlyBold.arrow_down_2),
  IconlyDetail(type: 'IconlyBold', title: 'arrow_down_3', iconData: IconlyBold.arrow_down_3),
  IconlyDetail(
      type: 'IconlyBold', title: 'arrow_down_circle', iconData: IconlyBold.arrow_down_circle),
  IconlyDetail(
      type: 'IconlyBold', title: 'arrow_down_square', iconData: IconlyBold.arrow_down_square),
  IconlyDetail(type: 'IconlyBold', title: 'arrow_left', iconData: IconlyBold.arrow_left),
  IconlyDetail(type: 'IconlyBold', title: 'arrow_left_2', iconData: IconlyBold.arrow_left_2),
  IconlyDetail(type: 'IconlyBold', title: 'arrow_left_3', iconData: IconlyBold.arrow_left_3),
  IconlyDetail(
      type: 'IconlyBold', title: 'arrow_left_circle', iconData: IconlyBold.arrow_left_circle),
  IconlyDetail(
      type: 'IconlyBold', title: 'arrow_left_square', iconData: IconlyBold.arrow_left_square),
  IconlyDetail(type: 'IconlyBold', title: 'arrow_right', iconData: IconlyBold.arrow_right),
  IconlyDetail(type: 'IconlyBold', title: 'arrow_right_2', iconData: IconlyBold.arrow_right_2),
  IconlyDetail(type: 'IconlyBold', title: 'arrow_right_3', iconData: IconlyBold.arrow_right_3),
  IconlyDetail(
      type: 'IconlyBold', title: 'arrow_right_circle', iconData: IconlyBold.arrow_right_circle),
  IconlyDetail(
      type: 'IconlyBold', title: 'arrow_right_square', iconData: IconlyBold.arrow_right_square),
  IconlyDetail(type: 'IconlyBold', title: 'arrow_up', iconData: IconlyBold.arrow_up),
  IconlyDetail(type: 'IconlyBold', title: 'arrow_up_2', iconData: IconlyBold.arrow_up_2),
  IconlyDetail(type: 'IconlyBold', title: 'arrow_up_3', iconData: IconlyBold.arrow_up_3),
  IconlyDetail(type: 'IconlyBold', title: 'arrow_up_circle', iconData: IconlyBold.arrow_up_circle),
  IconlyDetail(type: 'IconlyBold', title: 'arrow_up_square', iconData: IconlyBold.arrow_up_square),
  IconlyDetail(type: 'IconlyBold', title: 'bag', iconData: IconlyBold.bag),
  IconlyDetail(type: 'IconlyBold', title: 'bag_2', iconData: IconlyBold.bag_2),
  IconlyDetail(type: 'IconlyBold', title: 'bookmark', iconData: IconlyBold.bookmark),
  IconlyDetail(type: 'IconlyBold', title: 'buy', iconData: IconlyBold.buy),
  IconlyDetail(type: 'IconlyBold', title: 'calendar', iconData: IconlyBold.calendar),
  IconlyDetail(type: 'IconlyBold', title: 'call', iconData: IconlyBold.call),
  IconlyDetail(type: 'IconlyBold', title: 'call_missed', iconData: IconlyBold.call_missed),
  IconlyDetail(type: 'IconlyBold', title: 'call_silent', iconData: IconlyBold.call_silent),
  IconlyDetail(type: 'IconlyBold', title: 'calling', iconData: IconlyBold.calling),
  IconlyDetail(type: 'IconlyBold', title: 'camera', iconData: IconlyBold.camera),
  IconlyDetail(type: 'IconlyBold', title: 'category', iconData: IconlyBold.category),
  IconlyDetail(type: 'IconlyBold', title: 'chart', iconData: IconlyBold.chart),
  IconlyDetail(type: 'IconlyBold', title: 'chat', iconData: IconlyBold.chat),
  IconlyDetail(type: 'IconlyBold', title: 'close_square', iconData: IconlyBold.close_square),
  IconlyDetail(type: 'IconlyBold', title: 'danger', iconData: IconlyBold.danger),
  IconlyDetail(type: 'IconlyBold', title: 'delete', iconData: IconlyBold.delete),
  IconlyDetail(type: 'IconlyBold', title: 'discount', iconData: IconlyBold.discount),
  IconlyDetail(type: 'IconlyBold', title: 'discovery', iconData: IconlyBold.discovery),
  IconlyDetail(type: 'IconlyBold', title: 'document', iconData: IconlyBold.document),
  IconlyDetail(type: 'IconlyBold', title: 'download', iconData: IconlyBold.download),
  IconlyDetail(type: 'IconlyBold', title: 'edit', iconData: IconlyBold.edit),
  IconlyDetail(type: 'IconlyBold', title: 'editSquare', iconData: IconlyBold.editSquare),
  IconlyDetail(type: 'IconlyBold', title: 'filter', iconData: IconlyBold.filter),
  IconlyDetail(type: 'IconlyBold', title: 'filter_2', iconData: IconlyBold.filter_2),
  IconlyDetail(type: 'IconlyBold', title: 'folder', iconData: IconlyBold.folder),
  IconlyDetail(type: 'IconlyBold', title: 'game', iconData: IconlyBold.game),
  IconlyDetail(type: 'IconlyBold', title: 'graph', iconData: IconlyBold.graph),
  IconlyDetail(type: 'IconlyBold', title: 'heart', iconData: IconlyBold.heart),
  IconlyDetail(type: 'IconlyBold', title: 'hide', iconData: IconlyBold.hide),
  IconlyDetail(type: 'IconlyBold', title: 'home', iconData: IconlyBold.home),
  IconlyDetail(type: 'IconlyBold', title: 'image', iconData: IconlyBold.image),
  IconlyDetail(type: 'IconlyBold', title: 'image_2', iconData: IconlyBold.image_2),
  IconlyDetail(type: 'IconlyBold', title: 'info_circle', iconData: IconlyBold.info_circle),
  IconlyDetail(type: 'IconlyBold', title: 'info_square', iconData: IconlyBold.info_square),
  IconlyDetail(type: 'IconlyBold', title: 'location', iconData: IconlyBold.location),
  IconlyDetail(type: 'IconlyBold', title: 'lock', iconData: IconlyBold.lock),
  IconlyDetail(type: 'IconlyBold', title: 'login', iconData: IconlyBold.login),
  IconlyDetail(type: 'IconlyBold', title: 'logout', iconData: IconlyBold.logout),
  IconlyDetail(type: 'IconlyBold', title: 'message', iconData: IconlyBold.message),
  IconlyDetail(type: 'IconlyBold', title: 'more_circle', iconData: IconlyBold.more_circle),
  IconlyDetail(type: 'IconlyBold', title: 'more_square', iconData: IconlyBold.more_square),
  IconlyDetail(type: 'IconlyBold', title: 'notification', iconData: IconlyBold.notification),
  IconlyDetail(type: 'IconlyBold', title: 'paper', iconData: IconlyBold.paper),
  IconlyDetail(type: 'IconlyBold', title: 'paper_download', iconData: IconlyBold.paper_download),
  IconlyDetail(type: 'IconlyBold', title: 'paper_fail', iconData: IconlyBold.paper_fail),
  IconlyDetail(type: 'IconlyBold', title: 'paper_negative', iconData: IconlyBold.paper_negative),
  IconlyDetail(type: 'IconlyBold', title: 'paper_plus', iconData: IconlyBold.paper_plus),
  IconlyDetail(type: 'IconlyBold', title: 'paper_upload', iconData: IconlyBold.paper_upload),
  IconlyDetail(type: 'IconlyBold', title: 'password', iconData: IconlyBold.password),
  IconlyDetail(type: 'IconlyBold', title: 'play', iconData: IconlyBold.play),
  IconlyDetail(type: 'IconlyBold', title: 'plus', iconData: IconlyBold.plus),
  IconlyDetail(type: 'IconlyBold', title: 'profile', iconData: IconlyBold.profile),
  IconlyDetail(type: 'IconlyBold', title: 'scan', iconData: IconlyBold.scan),
  IconlyDetail(type: 'IconlyBold', title: 'search', iconData: IconlyBold.search),
  IconlyDetail(type: 'IconlyBold', title: 'send', iconData: IconlyBold.send),
  IconlyDetail(type: 'IconlyBold', title: 'setting', iconData: IconlyBold.setting),
  IconlyDetail(type: 'IconlyBold', title: 'shield_done', iconData: IconlyBold.shield_done),
  IconlyDetail(type: 'IconlyBold', title: 'shield_fail', iconData: IconlyBold.shield_fail),
  IconlyDetail(type: 'IconlyBold', title: 'show', iconData: IconlyBold.show),
  IconlyDetail(type: 'IconlyBold', title: 'star', iconData: IconlyBold.star),
  IconlyDetail(type: 'IconlyBold', title: 'swap', iconData: IconlyBold.swap),
  IconlyDetail(type: 'IconlyBold', title: 'tick_square', iconData: IconlyBold.tick_square),
  IconlyDetail(type: 'IconlyBold', title: 'ticket', iconData: IconlyBold.ticket),
  IconlyDetail(type: 'IconlyBold', title: 'ticket_star', iconData: IconlyBold.ticket_star),
  IconlyDetail(type: 'IconlyBold', title: 'time_circle', iconData: IconlyBold.time_circle),
  IconlyDetail(type: 'IconlyBold', title: 'time_square', iconData: IconlyBold.time_square),
  IconlyDetail(type: 'IconlyBold', title: 'unlock', iconData: IconlyBold.unlock),
  IconlyDetail(type: 'IconlyBold', title: 'upload', iconData: IconlyBold.upload),
  IconlyDetail(type: 'IconlyBold', title: 'user_2', iconData: IconlyBold.user_2),
  IconlyDetail(type: 'IconlyBold', title: 'user_3', iconData: IconlyBold.user_3),
  IconlyDetail(type: 'IconlyBold', title: 'video', iconData: IconlyBold.video),
  IconlyDetail(type: 'IconlyBold', title: 'voice', iconData: IconlyBold.voice),
  IconlyDetail(type: 'IconlyBold', title: 'voice_2', iconData: IconlyBold.voice_2),
  IconlyDetail(type: 'IconlyBold', title: 'volume_down', iconData: IconlyBold.volume_down),
  IconlyDetail(type: 'IconlyBold', title: 'volume_off', iconData: IconlyBold.volume_off),
  IconlyDetail(type: 'IconlyBold', title: 'volume_up', iconData: IconlyBold.volume_up),
  IconlyDetail(type: 'IconlyBold', title: 'wallet', iconData: IconlyBold.wallet),
  IconlyDetail(type: 'IconlyBold', title: 'work', iconData: IconlyBold.work),
];
